"""Patch Xgboost_0310.ipynb: replace df_struct cell source."""
import json

NB_PATH = r'e:\Xgboost\Xgboost_0310.ipynb'

with open(NB_PATH, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Identify the df_struct cell
target_idx = None
for i, cell in enumerate(nb['cells']):
    src = ''.join(cell.get('source', []))
    if 'N_STRUCT = 5000' in src and cell.get('cell_type') == 'code':
        target_idx = i
        break

assert target_idx is not None, 'df_struct cell not found'
print(f'Found df_struct cell at index {target_idx}')

lines = []
lines.append("import numpy as np\n")
lines.append("import random as _rnd\n")
lines.append("\n")
lines.append("N_STRUCT = 5000\n")
lines.append("\n")
lines.append("CITIES = [\n")
lines.append("    'Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Hangzhou',\n")
lines.append("    'Chengdu', 'Wuhan', 'Nanjing', \"Xi'an\", 'Tianjin',\n")
lines.append("    'Chongqing', 'Suzhou', 'Zhengzhou', 'Changsha'\n")
lines.append("]\n")
lines.append("GENDERS = ['Male', 'Female']\n")
lines.append("GENDER_WEIGHTS = [0.52, 0.48]\n")
lines.append("\n")
lines.append("JOB_LEVELS = ['Intern', 'Junior', 'Mid-level', 'Senior', 'Lead', 'Manager', 'Director', 'VP']\n")
lines.append("LEVEL_WEIGHTS_S = [0.05, 0.30, 0.20, 0.25, 0.10, 0.06, 0.03, 0.01]\n")
lines.append("\n")
lines.append("EDUCATION_LEVELS = ['High School', \"Bachelor's\", \"Master's\", 'Ph.D.']\n")
lines.append("EDU_WEIGHTS = [0.06, 0.48, 0.37, 0.09]\n")
lines.append("\n")
lines.append("POLITICAL_AFFILIATIONS = [\n")
lines.append("    'CPC Member', 'CPC Candidate',\n")
lines.append("    'Democratic Party Member', 'Non-affiliated'\n")
lines.append("]\n")
lines.append("POLITICAL_WEIGHTS = [0.30, 0.10, 0.05, 0.55]\n")
lines.append("\n")
lines.append("INDUSTRIES = df['Industry'].unique()\n")
lines.append("LEVEL_IDX  = {l: i for i, l in enumerate(JOB_LEVELS)}\n")
lines.append("EDU_IDX    = {'High School': 0, \"Bachelor's\": 1, \"Master's\": 2, 'Ph.D.': 3}\n")
lines.append("\n")
lines.append("# Experience bands (years)\n")
lines.append("EXP_BANDS = {\n")
lines.append("    'Intern':   (0, 1),  'Junior':   (0, 3),\n")
lines.append("    'Mid-level':(2, 7),  'Senior':   (5, 12),\n")
lines.append("    'Lead':     (7, 15), 'Manager':  (8, 18),\n")
lines.append("    'Director': (10,20), 'VP':       (12,25),\n")
lines.append("}\n")
lines.append("\n")
lines.append("# Expected annual salary bands (\u4e07/year), overall range 5-60\n")
lines.append("EXPECTED_SAL_BANDS = {\n")
lines.append("    'Intern':   (5,  10), 'Junior':   (8,  18),\n")
lines.append("    'Mid-level':(12, 28), 'Senior':   (18, 40),\n")
lines.append("    'Lead':     (25, 50), 'Manager':  (30, 55),\n")
lines.append("    'Director': (35, 60), 'VP':       (45, 60),\n")
lines.append("}\n")
lines.append("\n")
lines.append("def sample_with_missing(values, size, missing_rate):\n")
lines.append("    arr = np.array(values, dtype=object)\n")
lines.append("    arr[np.random.rand(size) < missing_rate] = np.nan\n")
lines.append("    return arr\n")
lines.append("\n")
lines.append("def gen_expected_salary(level):\n")
lines.append("    \"\"\"95% integer (62% end in 0/5), 5% one-decimal float.\"\"\"\n")
lines.append("    lo, hi = EXPECTED_SAL_BANDS[level]\n")
lines.append("    if _rnd.random() < 0.05:\n")
lines.append("        return round(_rnd.uniform(lo, hi), 1)\n")
lines.append("    raw = _rnd.uniform(lo, hi)\n")
lines.append("    if _rnd.random() < 0.62:\n")
lines.append("        return float(max(lo, min(hi, round(raw / 5) * 5)))\n")
lines.append("    return float(round(raw))\n")
lines.append("\n")
lines.append("# Title perturbation pairs\n")
lines.append("TITLE_SYNONYMS = [\n")
lines.append("    ('Senior', 'Sr.'), ('Junior', 'Jr.'),\n")
lines.append("    ('Manager', 'Head of'), ('Engineer', 'Developer'),\n")
lines.append("    ('Analyst', 'Specialist'), ('UI/UX', 'UX/UI'),\n")
lines.append("    ('Machine Learning', 'ML'), ('Data Science', 'Data Analytics'),\n")
lines.append("    ('Game ', 'Gaming '), ('Cyber', 'InfoSec'),\n")
lines.append("    ('Product Manager', 'Product Lead'),\n")
lines.append("]\n")
lines.append("\n")
lines.append("def perturb_title(title):\n")
lines.append("    for orig, repl in TITLE_SYNONYMS:\n")
lines.append("        if orig in title:\n")
lines.append("            return title.replace(orig, repl, 1)\n")
lines.append("    words = title.split()\n")
lines.append("    return (' '.join([words[1], words[0]] + words[2:]) if len(words) >= 2 else title)\n")
lines.append("\n")
lines.append("# Per-industry title & skill pools from df_jd\n")
lines.append("from collections import defaultdict\n")
lines.append("_ind_titles = defaultdict(list)\n")
lines.append("_ind_skills = defaultdict(list)\n")
lines.append("for _, _r in df_jd.iterrows():\n")
lines.append("    _ind_titles[_r['Industry']].append(_r['Job Title'])\n")
lines.append("    _ind_skills[_r['Industry']].extend(\n")
lines.append("        [s.strip() for s in str(_r['Skills']).split(',') if s.strip()])\n")
lines.append("for _k in _ind_skills:\n")
lines.append("    _ind_skills[_k] = list(set(_ind_skills[_k]))\n")
lines.append("_global_skills = list(set(\n")
lines.append("    s.strip() for sk in df_jd['Skills'] for s in sk.split(',') if s.strip()))\n")
lines.append("\n")
lines.append("def get_expected_title(industry, idx):\n")
lines.append("    pool  = _ind_titles.get(industry) or df_jd['Job Title'].tolist()\n")
lines.append("    title = _rnd.choice(pool)\n")
lines.append("    return perturb_title(title) if idx % 5 == 0 else title\n")
lines.append("\n")
lines.append("def get_candidate_skills(industry):\n")
lines.append("    pool = _ind_skills.get(industry) or _global_skills\n")
lines.append("    n    = _rnd.randint(5, 8)\n")
lines.append("    return ', '.join(_rnd.sample(pool, min(n, len(pool))))\n")
lines.append("\n")
lines.append("# Core attributes\n")
lines.append("job_levels_s = np.random.choice(JOB_LEVELS, size=N_STRUCT, p=LEVEL_WEIGHTS_S)\n")
lines.append("industries_s = np.random.choice(INDUSTRIES, size=N_STRUCT)\n")
lines.append("cities_s     = np.random.choice(CITIES,     size=N_STRUCT)\n")
lines.append("genders_s    = np.random.choice(GENDERS,    size=N_STRUCT, p=GENDER_WEIGHTS)\n")
lines.append("educations_s = np.random.choice(EDUCATION_LEVELS, size=N_STRUCT, p=EDU_WEIGHTS)\n")
lines.append("politics_s   = np.random.choice(POLITICAL_AFFILIATIONS, size=N_STRUCT, p=POLITICAL_WEIGHTS)\n")
lines.append("\n")
lines.append("# Numerical features\n")
lines.append("years_exp = np.array([_rnd.randint(*EXP_BANDS[l]) for l in job_levels_s], dtype=float)\n")
lines.append("age = np.clip(\n")
lines.append("    years_exp + np.random.randint(22, 28, N_STRUCT) + np.random.randint(-2, 3, N_STRUCT),\n")
lines.append("    18, 60).astype(float)\n")
lines.append("expected_salary  = np.array([gen_expected_salary(l) for l in job_levels_s], dtype=float)\n")
lines.append("base_hours       = np.where(np.isin(job_levels_s, ['Manager', 'Director', 'VP']),\n")
lines.append("                            np.random.normal(50, 6, N_STRUCT),\n")
lines.append("                            np.random.normal(44, 5, N_STRUCT))\n")
lines.append("weekly_hours     = np.clip(base_hours, 30, 80).round(1)\n")
lines.append("num_applications = np.random.poisson(lam=8, size=N_STRUCT).astype(float)\n")
lines.append("expected_titles  = [get_expected_title(ind, i) for i, ind in enumerate(industries_s)]\n")
lines.append("skills_s         = [get_candidate_skills(ind) for ind in industries_s]\n")
lines.append("\n")
lines.append("# Introduce missing values\n")
lines.append("years_exp        = sample_with_missing(years_exp,        N_STRUCT, 0.05)\n")
lines.append("expected_salary  = sample_with_missing(expected_salary,  N_STRUCT, 0.08)\n")
lines.append("age              = sample_with_missing(age,              N_STRUCT, 0.06)\n")
lines.append("weekly_hours     = sample_with_missing(weekly_hours,     N_STRUCT, 0.08)\n")
lines.append("num_applications = sample_with_missing(num_applications, N_STRUCT, 0.04)\n")
lines.append("cities_m         = sample_with_missing(cities_s,         N_STRUCT, 0.07)\n")
lines.append("educations_m     = sample_with_missing(educations_s,     N_STRUCT, 0.05)\n")
lines.append("politics_m       = sample_with_missing(politics_s,       N_STRUCT, 0.10)\n")
lines.append("\n")
lines.append("# Assemble DataFrame\n")
lines.append("df_struct = pd.DataFrame({\n")
lines.append("    'record_id':             [f'REC_{i:05d}' for i in range(1, N_STRUCT + 1)],\n")
lines.append("    'years_experience':      years_exp.astype(float),\n")
lines.append("    'expected_salary_k':     expected_salary.astype(float),\n")
lines.append("    'age':                   age.astype(float),\n")
lines.append("    'weekly_hours':          weekly_hours.astype(float),\n")
lines.append("    'num_applications':      num_applications.astype(float),\n")
lines.append("    'gender':                genders_s,\n")
lines.append("    'job_level':             job_levels_s,\n")
lines.append("    'industry':              industries_s,\n")
lines.append("    'city':                  cities_m,\n")
lines.append("    'education_level':       educations_m,\n")
lines.append("    'political_affiliation': politics_m,\n")
lines.append("    'expected_title':        expected_titles,\n")
lines.append("    'skills':                skills_s,\n")
lines.append("})\n")
lines.append("edu_order   = {v: i for i, v in enumerate(EDUCATION_LEVELS)}\n")
lines.append("level_order = {v: i for i, v in enumerate(JOB_LEVELS)}\n")
lines.append("df_struct['education_ordinal'] = df_struct['education_level'].map(edu_order)\n")
lines.append("df_struct['job_level_ordinal']  = df_struct['job_level'].map(level_order)\n")
lines.append("\n")
lines.append("# Ground Truth: vectorised heuristic (N x M matrices)\n")
lines.append("# Score = industry×3 + level_proximity×2 + salary_match×2 + edu_meets_req×1\n")
lines.append("# expected_salary_k unit: \u4e07/year; convert to monthly k: x * 10/12\n")
lines.append("print('Computing ground truth labels (vectorised) ...')\n")
lines.append("\n")
lines.append("_edu_col = 'edu_req' if 'edu_req' in df_jd.columns else None\n")
lines.append("j_ind = df_jd['Industry'].values\n")
lines.append("j_lvl = np.array([LEVEL_IDX.get(l, 3) for l in df_jd['job_level'].values])\n")
lines.append("j_sal = df_jd['salary_mid'].values.astype(float)\n")
lines.append("j_edu = (np.array([EDU_IDX.get(e, 1) for e in df_jd[_edu_col].values])\n")
lines.append("         if _edu_col else np.ones(len(df_jd), dtype=int))\n")
lines.append("\n")
lines.append("p_ind = df_struct['industry'].values\n")
lines.append("p_lvl = np.array([LEVEL_IDX.get(l, 3) for l in df_struct['job_level'].values])\n")
lines.append("p_sal = df_struct['expected_salary_k'].values.astype(float) * 10 / 12\n")
lines.append("p_edu = np.array([EDU_IDX.get(str(e), 1) for e in df_struct['education_level'].values])\n")
lines.append("\n")
lines.append("ind_score = (p_ind[:, None] == j_ind[None, :]).astype(np.float32) * 3.0\n")
lines.append("lvl_diff  = np.abs(p_lvl[:, None].astype(np.float32) - j_lvl[None, :].astype(np.float32))\n")
lines.append("lvl_score = np.maximum(0.0, 1.0 - lvl_diff * 0.3) * 2.0\n")
lines.append("p_s2d  = np.where(np.isnan(p_sal), 0.0, p_sal)[:, None].astype(np.float32)\n")
lines.append("j_s2d  = j_sal[None, :].astype(np.float32)\n")
lines.append("max_s  = np.maximum(p_s2d, j_s2d)\n")
lines.append("sal_score = np.where(max_s > 0, np.minimum(p_s2d, j_s2d) / max_s, 0.5).astype(np.float32) * 2.0\n")
lines.append("sal_score[np.isnan(p_sal)] = 1.0\n")
lines.append("edu_score = (p_edu[:, None] >= j_edu[None, :]).astype(np.float32)\n")
lines.append("\n")
lines.append("best_idxs = np.argmax(ind_score + lvl_score + sal_score + edu_score, axis=1)\n")
lines.append("df_struct['ground_truth_jd_id'] = df_jd['jd_id'].iloc[best_idxs].values\n")
lines.append("\n")
lines.append("print(f'Structured dataset shape: {df_struct.shape}')\n")
lines.append("print(df_struct[['record_id', 'job_level', 'industry',\n")
lines.append("                  'expected_salary_k', 'expected_title',\n")
lines.append("                  'ground_truth_jd_id']].head(8).to_string())\n")
lines.append("print(f\"\\nGround truth: {df_struct['ground_truth_jd_id'].nunique()} unique JDs / {len(df_jd)} total\")\n")
lines.append("df_struct.head(5)")

nb['cells'][target_idx]['source'] = lines
nb['cells'][target_idx]['outputs'] = []
nb['cells'][target_idx]['execution_count'] = None
if 'id' not in nb['cells'][target_idx]:
    nb['cells'][target_idx]['id'] = 'struct_gen_cell'

with open(NB_PATH, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f'Patched cell {target_idx}. Notebook saved.')
